name: jupyter-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - scikit-rf
  - schemdraw
  - pip
  - setuptools
  - jupyterlab
  - pip:
    - jupyterlab_latex